import calculateCombinedAssetRanks from '../calculateCombinedAssetRanks';

// --- Unit Test Implementation ---
const FSADataFromR = [
    {
        "GEO_NAME": "N0B",
        "Median_age_of_the_population": 42.8,
        "GEO_DISPLAY_NAME": "Wellesley & rural",
        "Average_age_of_the_population": 41.3,
        "Population": 86919,
        "Total_private_dwellings": 31269,
        "arena": 0,
        "community_centre": 2,
        "miscellaneous": 2,
        "park": 2,
        "playground": 0,
        "pool": 2,
        "rink": 0,
        "splash_pad": 1,
        "sports_field": 1,
        "stadium": 0,
        "trail": 20,
        "parks_per_capita_standardized": -1.25902,
        "pools_per_capita_standardized": -1.1221,
        "community_centre_per_capita_standardized": -0.391637,
        "trails_per_capita_standardized": -0.651782,
        "combined_metric": -0.856133,
        "combined_rank": 23,
        "parks_per_capita": 0.0000230099,
        "pools_per_capita": 0.0000230099,
        "community_centre_per_capita": 0.0000230099,
        "trails_per_capita": 0.000230099
    },
    {
        "GEO_NAME": "N1P",
        "Median_age_of_the_population": 36,
        "GEO_DISPLAY_NAME": "Cambridge",
        "Average_age_of_the_population": 35.7,
        "Population": 7991,
        "Total_private_dwellings": 2526,
        "arena": 0,
        "community_centre": 0,
        "miscellaneous": 0,
        "park": 3,
        "playground": 0,
        "pool": 0,
        "rink": 0,
        "splash_pad": 0,
        "sports_field": 3,
        "stadium": 0,
        "trail": 6,
        "parks_per_capita_standardized": -0.817329,
        "pools_per_capita_standardized": -1.26347,
        "community_centre_per_capita_standardized": -0.802412,
        "trails_per_capita_standardized": -0.38085,
        "combined_metric": -0.816016,
        "combined_rank": 22,
        "parks_per_capita": 0.000375422,
        "pools_per_capita": 0,
        "community_centre_per_capita": 0,
        "trails_per_capita": 0.000750845
    },
    {
        "GEO_NAME": "N1R",
        "Median_age_of_the_population": 40.8,
        "GEO_DISPLAY_NAME": "Cambridge",
        "Average_age_of_the_population": 41.9,
        "Population": 42928,
        "Total_private_dwellings": 18081,
        "arena": 0,
        "community_centre": 0,
        "miscellaneous": 3,
        "park": 28,
        "playground": 0,
        "pool": 11,
        "rink": 4,
        "splash_pad": 4,
        "sports_field": 29,
        "stadium": 0,
        "trail": 35,
        "parks_per_capita_standardized": -0.470368,
        "pools_per_capita_standardized": 0.310934,
        "community_centre_per_capita_standardized": -0.802412,
        "trails_per_capita_standardized": -0.347305,
        "combined_metric": -0.327288,
        "combined_rank": 17,
        "parks_per_capita": 0.000652255,
        "pools_per_capita": 0.000256243,
        "community_centre_per_capita": 0,
        "trails_per_capita": 0.000815319
    },
    {
        "GEO_NAME": "N1S",
        "Median_age_of_the_population": 42.8,
        "GEO_DISPLAY_NAME": "Cambridge",
        "Average_age_of_the_population": 42.5,
        "Population": 20171,
        "Total_private_dwellings": 8187,
        "arena": 0,
        "community_centre": 0,
        "miscellaneous": 0,
        "park": 29,
        "playground": 0,
        "pool": 3,
        "rink": 3,
        "splash_pad": 0,
        "sports_field": 13,
        "stadium": 0,
        "trail": 16,
        "parks_per_capita_standardized": 0.514058,
        "pools_per_capita_standardized": -0.349657,
        "community_centre_per_capita_standardized": -0.802412,
        "trails_per_capita_standardized": -0.358804,
        "combined_metric": -0.249204,
        "combined_rank": 15,
        "parks_per_capita": 0.00143771,
        "pools_per_capita": 0.000148728,
        "community_centre_per_capita": 0,
        "trails_per_capita": 0.000793218
    },
    {
        "GEO_NAME": "N1T",
        "Median_age_of_the_population": 37.2,
        "GEO_DISPLAY_NAME": "Cambridge east",
        "Average_age_of_the_population": 37.5,
        "Population": 18513,
        "Total_private_dwellings": 5647,
        "arena": 0,
        "community_centre": 0,
        "miscellaneous": 0,
        "park": 6,
        "playground": 0,
        "pool": 3,
        "rink": 1,
        "splash_pad": 1,
        "sports_field": 15,
        "stadium": 0,
        "trail": 23,
        "parks_per_capita_standardized": -0.881657,
        "pools_per_capita_standardized": -0.267817,
        "community_centre_per_capita_standardized": -0.802412,
        "trails_per_capita_standardized": -0.12512,
        "combined_metric": -0.519252,
        "combined_rank": 21,
        "parks_per_capita": 0.000324097,
        "pools_per_capita": 0.000162048,
        "community_centre_per_capita": 0,
        "trails_per_capita": 0.00124237
    },
    {
        "GEO_NAME": "N2A",
        "Median_age_of_the_population": 39.2,
        "GEO_DISPLAY_NAME": "Stanley Park",
        "Average_age_of_the_population": 39.9,
        "Population": 32454,
        "Total_private_dwellings": 12178,
        "arena": 0,
        "community_centre": 3,
        "miscellaneous": 0,
        "park": 43,
        "playground": 22,
        "pool": 9,
        "rink": 0,
        "splash_pad": 1,
        "sports_field": 39,
        "stadium": 0,
        "trail": 14,
        "parks_per_capita_standardized": 0.372739,
        "pools_per_capita_standardized": 0.440408,
        "community_centre_per_capita_standardized": 0.847809,
        "trails_per_capita_standardized": -0.54706,
        "combined_metric": 0.278474,
        "combined_rank": 8,
        "parks_per_capita": 0.00132495,
        "pools_per_capita": 0.000277316,
        "community_centre_per_capita": 0.0000924385,
        "trails_per_capita": 0.00043138
    },
    {
        "GEO_NAME": "N2B",
        "Median_age_of_the_population": 42.8,
        "GEO_DISPLAY_NAME": "Kitchener South of Victoria",
        "Average_age_of_the_population": 42.8,
        "Population": 16939,
        "Total_private_dwellings": 7329,
        "arena": 1,
        "community_centre": 0,
        "miscellaneous": 0,
        "park": 17,
        "playground": 11,
        "pool": 2,
        "rink": 0,
        "splash_pad": 0,
        "sports_field": 22,
        "stadium": 0,
        "trail": 10,
        "parks_per_capita_standardized": -0.0300178,
        "pools_per_capita_standardized": -0.538024,
        "community_centre_per_capita_standardized": -0.802412,
        "trails_per_capita_standardized": -0.464349,
        "combined_metric": -0.458701,
        "combined_rank": 19,
        "parks_per_capita": 0.0010036,
        "pools_per_capita": 0.000118071,
        "community_centre_per_capita": 0,
        "trails_per_capita": 0.000590354
    },
    {
        "GEO_NAME": "N2C",
        "Median_age_of_the_population": 36.8,
        "GEO_DISPLAY_NAME": "Kitchener Fairway",
        "Average_age_of_the_population": 40.3,
        "Population": 17681,
        "Total_private_dwellings": 7494,
        "arena": 1,
        "community_centre": 2,
        "miscellaneous": 0,
        "park": 32,
        "playground": 11,
        "pool": 7,
        "rink": 0,
        "splash_pad": 3,
        "sports_field": 34,
        "stadium": 0,
        "trail": 10,
        "parks_per_capita_standardized": 0.980476,
        "pools_per_capita_standardized": 1.16905,
        "community_centre_per_capita_standardized": 1.21694,
        "trails_per_capita_standardized": -0.477239,
        "combined_metric": 0.722306,
        "combined_rank": 2,
        "parks_per_capita": 0.00180985,
        "pools_per_capita": 0.000395905,
        "community_centre_per_capita": 0.000113116,
        "trails_per_capita": 0.000565579
    },
    {
        "GEO_NAME": "N2E",
        "Median_age_of_the_population": 36.4,
        "GEO_DISPLAY_NAME": "Kitchener Southwest",
        "Average_age_of_the_population": 37.7,
        "Population": 40428,
        "Total_private_dwellings": 14544,
        "arena": 1,
        "community_centre": 4,
        "miscellaneous": 0,
        "park": 41,
        "playground": 28,
        "pool": 3,
        "rink": 0,
        "splash_pad": 2,
        "sports_field": 51,
        "stadium": 0,
        "trail": 10,
        "parks_per_capita_standardized": -0.0167985,
        "pools_per_capita_standardized": -0.807537,
        "community_centre_per_capita_standardized": 0.963898,
        "trails_per_capita_standardized": -0.642805,
        "combined_metric": -0.125811,
        "combined_rank": 13,
        "parks_per_capita": 0.00101415,
        "pools_per_capita": 0.000074206,
        "community_centre_per_capita": 0.0000989413,
        "trails_per_capita": 0.000247353
    },
    {
        "GEO_NAME": "N2G",
        "Median_age_of_the_population": 38,
        "GEO_DISPLAY_NAME": "Kitchener Downtown",
        "Average_age_of_the_population": 42.2,
        "Population": 14580,
        "Total_private_dwellings": 8284,
        "arena": 1,
        "community_centre": 3,
        "miscellaneous": 0,
        "park": 22,
        "playground": 9,
        "pool": 9,
        "rink": 0,
        "splash_pad": 1,
        "sports_field": 17,
        "stadium": 0,
        "trail": 10,
        "parks_per_capita_standardized": 0.603306,
        "pools_per_capita_standardized": 2.52924,
        "community_centre_per_capita_standardized": 2.87086,
        "trails_per_capita_standardized": -0.414654,
        "combined_metric": 1.39719,
        "combined_rank": 1,
        "parks_per_capita": 0.00150892,
        "pools_per_capita": 0.000617284,
        "community_centre_per_capita": 0.000205761,
        "trails_per_capita": 0.000685871
    },
    {
        "GEO_NAME": "N2H",
        "Median_age_of_the_population": 38.4,
        "GEO_DISPLAY_NAME": "Kitchener Victoria St",
        "Average_age_of_the_population": 41.1,
        "Population": 22456,
        "Total_private_dwellings": 11453,
        "arena": 1,
        "community_centre": 3,
        "miscellaneous": 0,
        "park": 41,
        "playground": 21,
        "pool": 7,
        "rink": 1,
        "splash_pad": 1,
        "sports_field": 29,
        "stadium": 0,
        "trail": 12,
        "parks_per_capita_standardized": 1.00045,
        "pools_per_capita_standardized": 0.651799,
        "community_centre_per_capita_standardized": 1.58253,
        "trails_per_capita_standardized": -0.493472,
        "combined_metric": 0.685328,
        "combined_rank": 3,
        "parks_per_capita": 0.00182579,
        "pools_per_capita": 0.000311721,
        "community_centre_per_capita": 0.000133595,
        "trails_per_capita": 0.000534378
    },
    {
        "GEO_NAME": "N2J",
        "Median_age_of_the_population": 36.8,
        "GEO_DISPLAY_NAME": "St Jacobs & Waterloo",
        "Average_age_of_the_population": 41.7,
        "Population": 20899,
        "Total_private_dwellings": 10672,
        "arena": 0,
        "community_centre": 1,
        "miscellaneous": 1,
        "park": 0,
        "playground": 5,
        "pool": 6,
        "rink": 4,
        "splash_pad": 1,
        "sports_field": 1,
        "stadium": 0,
        "trail": 55,
        "parks_per_capita_standardized": -1.28785,
        "pools_per_capita_standardized": 0.500495,
        "community_centre_per_capita_standardized": 0.0517961,
        "trails_per_capita_standardized": 0.597719,
        "combined_metric": -0.0344611,
        "combined_rank": 11,
        "parks_per_capita": 0,
        "pools_per_capita": 0.000287095,
        "community_centre_per_capita": 0.0000478492,
        "trails_per_capita": 0.0026317
    },
    {
        "GEO_NAME": "N2K",
        "Median_age_of_the_population": 40.4,
        "GEO_DISPLAY_NAME": "Waterloo East",
        "Average_age_of_the_population": 39.8,
        "Population": 29381,
        "Total_private_dwellings": 10815,
        "arena": 0,
        "community_centre": 2,
        "miscellaneous": 0,
        "park": 26,
        "playground": 32,
        "pool": 4,
        "rink": 6,
        "splash_pad": 1,
        "sports_field": 23,
        "stadium": 1,
        "trail": 151,
        "parks_per_capita_standardized": -0.178757,
        "pools_per_capita_standardized": -0.426988,
        "community_centre_per_capita_standardized": 0.412802,
        "trails_per_capita_standardized": 1.9024,
        "combined_metric": 0.427365,
        "combined_rank": 5,
        "parks_per_capita": 0.000884926,
        "pools_per_capita": 0.000136142,
        "community_centre_per_capita": 0.0000680712,
        "trails_per_capita": 0.00513938
    },
    {
        "GEO_NAME": "N2L",
        "Median_age_of_the_population": 29.8,
        "GEO_DISPLAY_NAME": "UW",
        "Average_age_of_the_population": 37.4,
        "Population": 37953,
        "Total_private_dwellings": 19681,
        "arena": 0,
        "community_centre": 0,
        "miscellaneous": 0,
        "park": 0,
        "playground": 12,
        "pool": 17,
        "rink": 5,
        "splash_pad": 2,
        "sports_field": 1,
        "stadium": 0,
        "trail": 125,
        "parks_per_capita_standardized": -1.28785,
        "pools_per_capita_standardized": 1.48865,
        "community_centre_per_capita_standardized": -0.802412,
        "trails_per_capita_standardized": 0.942061,
        "combined_metric": 0.0851109,
        "combined_rank": 9,
        "parks_per_capita": 0,
        "pools_per_capita": 0.000447922,
        "community_centre_per_capita": 0,
        "trails_per_capita": 0.00329355
    },
    {
        "GEO_NAME": "N2M",
        "Median_age_of_the_population": 36.4,
        "GEO_DISPLAY_NAME": "Kitchener West",
        "Average_age_of_the_population": 39.2,
        "Population": 36494,
        "Total_private_dwellings": 16113,
        "arena": 0,
        "community_centre": 2,
        "miscellaneous": 0,
        "park": 47,
        "playground": 30,
        "pool": 8,
        "rink": 0,
        "splash_pad": 0,
        "sports_field": 42,
        "stadium": 0,
        "trail": 7,
        "parks_per_capita_standardized": 0.326279,
        "pools_per_capita_standardized": 0.0834209,
        "community_centre_per_capita_standardized": 0.175946,
        "trails_per_capita_standardized": -0.671701,
        "combined_metric": -0.0215139,
        "combined_rank": 10,
        "parks_per_capita": 0.00128788,
        "pools_per_capita": 0.000219214,
        "community_centre_per_capita": 0.0000548035,
        "trails_per_capita": 0.000191812
    },
    {
        "GEO_NAME": "N2N",
        "Median_age_of_the_population": 39.2,
        "GEO_DISPLAY_NAME": "Kitchener West",
        "Average_age_of_the_population": 39.9,
        "Population": 26596,
        "Total_private_dwellings": 9145,
        "arena": 0,
        "community_centre": 2,
        "miscellaneous": 0,
        "park": 43,
        "playground": 22,
        "pool": 2,
        "rink": 0,
        "splash_pad": 0,
        "sports_field": 38,
        "stadium": 0,
        "trail": 7,
        "parks_per_capita_standardized": 0.738499,
        "pools_per_capita_standardized": -0.801434,
        "community_centre_per_capita_standardized": 0.540053,
        "trails_per_capita_standardized": -0.634561,
        "combined_metric": -0.039361,
        "combined_rank": 12,
        "parks_per_capita": 0.00161678,
        "pools_per_capita": 0.0000751993,
        "community_centre_per_capita": 0.0000751993,
        "trails_per_capita": 0.000263197
    },
    {
        "GEO_NAME": "N2P",
        "Median_age_of_the_population": 36,
        "GEO_DISPLAY_NAME": "Doon",
        "Average_age_of_the_population": 37,
        "Population": 25040,
        "Total_private_dwellings": 8848,
        "arena": 2,
        "community_centre": 2,
        "miscellaneous": 0,
        "park": 76,
        "playground": 19,
        "pool": 3,
        "rink": 0,
        "splash_pad": 1,
        "sports_field": 31,
        "stadium": 0,
        "trail": 10,
        "parks_per_capita_standardized": 2.51616,
        "pools_per_capita_standardized": -0.527348,
        "community_centre_per_capita_standardized": 0.623474,
        "trails_per_capita_standardized": -0.563719,
        "combined_metric": 0.512143,
        "combined_rank": 4,
        "parks_per_capita": 0.00303514,
        "pools_per_capita": 0.000119808,
        "community_centre_per_capita": 0.0000798722,
        "trails_per_capita": 0.000399361
    },
    {
        "GEO_NAME": "N2R",
        "Median_age_of_the_population": 32.8,
        "GEO_DISPLAY_NAME": "Kitchener Southwest",
        "Average_age_of_the_population": 32.3,
        "Population": 18445,
        "Total_private_dwellings": 5835,
        "arena": 0,
        "community_centre": 0,
        "miscellaneous": 0,
        "park": 40,
        "playground": 14,
        "pool": 0,
        "rink": 0,
        "splash_pad": 0,
        "sports_field": 17,
        "stadium": 0,
        "trail": 14,
        "parks_per_capita_standardized": 1.43011,
        "pools_per_capita_standardized": -1.26347,
        "community_centre_per_capita_standardized": -0.802412,
        "trails_per_capita_standardized": -0.3766,
        "combined_metric": -0.253093,
        "combined_rank": 16,
        "parks_per_capita": 0.00216861,
        "pools_per_capita": 0,
        "community_centre_per_capita": 0,
        "trails_per_capita": 0.000759013
    },
    {
        "GEO_NAME": "N2T",
        "Median_age_of_the_population": 41.2,
        "GEO_DISPLAY_NAME": "Waterloo West",
        "Average_age_of_the_population": 40.2,
        "Population": 20634,
        "Total_private_dwellings": 7109,
        "arena": 0,
        "community_centre": 0,
        "miscellaneous": 0,
        "park": 0,
        "playground": 16,
        "pool": 9,
        "rink": 5,
        "splash_pad": 0,
        "sports_field": 1,
        "stadium": 0,
        "trail": 117,
        "parks_per_capita_standardized": -1.28785,
        "pools_per_capita_standardized": 1.41646,
        "community_centre_per_capita_standardized": -0.802412,
        "trails_per_capita_standardized": 2.17861,
        "combined_metric": 0.3762,
        "combined_rank": 6,
        "parks_per_capita": 0,
        "pools_per_capita": 0.000436173,
        "community_centre_per_capita": 0,
        "trails_per_capita": 0.00567025
    },
    {
        "GEO_NAME": "N2V",
        "Median_age_of_the_population": 38,
        "GEO_DISPLAY_NAME": "Vista Hills",
        "Average_age_of_the_population": 37.9,
        "Population": 19428,
        "Total_private_dwellings": 6360,
        "arena": 0,
        "community_centre": 0,
        "miscellaneous": 0,
        "park": 0,
        "playground": 27,
        "pool": 6,
        "rink": 3,
        "splash_pad": 0,
        "sports_field": 1,
        "stadium": 0,
        "trail": 135,
        "parks_per_capita_standardized": -1.28785,
        "pools_per_capita_standardized": 0.634054,
        "community_centre_per_capita_standardized": -0.802412,
        "trails_per_capita_standardized": 2.84377,
        "combined_metric": 0.34689,
        "combined_rank": 7,
        "parks_per_capita": 0,
        "pools_per_capita": 0.000308833,
        "community_centre_per_capita": 0,
        "trails_per_capita": 0.00694873
    },
    {
        "GEO_NAME": "N3C",
        "Median_age_of_the_population": 38.8,
        "GEO_DISPLAY_NAME": "Cambridge 401 east",
        "Average_age_of_the_population": 38.7,
        "Population": 27518,
        "Total_private_dwellings": 9657,
        "arena": 0,
        "community_centre": 0,
        "miscellaneous": 0,
        "park": 30,
        "playground": 0,
        "pool": 3,
        "rink": 2,
        "splash_pad": 4,
        "sports_field": 19,
        "stadium": 0,
        "trail": 14,
        "parks_per_capita_standardized": 0.0785129,
        "pools_per_capita_standardized": -0.593636,
        "community_centre_per_capita_standardized": -0.802412,
        "trails_per_capita_standardized": -0.506802,
        "combined_metric": -0.456084,
        "combined_rank": 18,
        "parks_per_capita": 0.0010902,
        "pools_per_capita": 0.00010902,
        "community_centre_per_capita": 0,
        "trails_per_capita": 0.000508758
    },
    {
        "GEO_NAME": "N3E",
        "Median_age_of_the_population": 30.8,
        "GEO_DISPLAY_NAME": "Cambridge East",
        "Average_age_of_the_population": 30.7,
        "Population": 2802,
        "Total_private_dwellings": 839,
        "arena": 0,
        "community_centre": 0,
        "miscellaneous": 0,
        "park": 4,
        "playground": 0,
        "pool": 0,
        "rink": 0,
        "splash_pad": 0,
        "sports_field": 0,
        "stadium": 0,
        "trail": 2,
        "parks_per_capita_standardized": 0.501329,
        "pools_per_capita_standardized": -1.26347,
        "community_centre_per_capita_standardized": -0.802412,
        "trails_per_capita_standardized": -0.400136,
        "combined_metric": -0.491173,
        "combined_rank": 20,
        "parks_per_capita": 0.00142755,
        "pools_per_capita": 0,
        "community_centre_per_capita": 0,
        "trails_per_capita": 0.000713776
    },
    {
        "GEO_NAME": "N3H",
        "Median_age_of_the_population": 40.8,
        "GEO_DISPLAY_NAME": "Sportsworld",
        "Average_age_of_the_population": 41.9,
        "Population": 24306,
        "Total_private_dwellings": 10220,
        "arena": 0,
        "community_centre": 1,
        "miscellaneous": 0,
        "park": 20,
        "playground": 0,
        "pool": 5,
        "rink": 2,
        "splash_pad": 2,
        "sports_field": 29,
        "stadium": 0,
        "trail": 17,
        "parks_per_capita_standardized": -0.256567,
        "pools_per_capita_standardized": 0.000452181,
        "community_centre_per_capita_standardized": -0.0679393,
        "trails_per_capita_standardized": -0.407607,
        "combined_metric": -0.182915,
        "combined_rank": 14,
        "parks_per_capita": 0.000822842,
        "pools_per_capita": 0.000205711,
        "community_centre_per_capita": 0.0000411421,
        "trails_per_capita": 0.000699416
    }
]

function runTest() {
    console.log("Running unit test for calculateCombinedRank...");
    
    // 2. Define the expected output from the R script, extracted from your data.
    // create an object mapping GEO_NAME to data for easy lookup
    const expectedCombinedMetricFromR = FSADataFromR.reduce((acc, d) => {
        acc[d.GEO_NAME] = d.combined_metric;
        return acc;
    }, {});

    const FSAFilters = { parks: true, pools: true, centres: true, trails: true };

    // 3. Run the function with the test data.
    const actualResult = calculateCombinedAssetRanks(FSAFilters, FSADataFromR);

    // 4. Assert and check the results.
    let testsPassed = true;
    let failedTests = [];
    actualResult.forEach(fsa => {
        const expectedRank = expectedCombinedMetricFromR[fsa.GEO_NAME];
        const actualRank = fsa.combined_metric;

        if (expectedRank.toFixed(5) === actualRank.toFixed(5)) {
            console.log(`✅ PASSED: For FSA ${fsa.GEO_NAME}, expected rank ${expectedRank}, got ${actualRank}.`);
        } else {
            console.error(`❌ FAILED: For FSA ${fsa.GEO_NAME}, expected rank ${expectedRank}, but got ${actualRank}.`);
            testsPassed = false;
            failedTests.push({fsa: fsa.GEO_NAME, expected: expectedRank, actual: actualRank});
        }
    });

    console.log("\n--------------------");
    if (testsPassed) {
        console.log("All tests passed successfully!");
    } else {
        console.log(`${failedTests.length} test(s) failed.`);
        console.table(failedTests);
    }
    console.log("--------------------");

    // Display the full output for inspection
    console.log("\nFull calculation result from JavaScript:");
    console.table(actualResult.map(d => ({
        FSA: d.GEO_NAME,
        Combined_Metric: d.combined_metric.toFixed(6), // Increased precision for debugging
        Rank: d.combined_rank,
    })));
}

// --- Execute the test ---
runTest();
